sync_length = floor(DATA_LENGTH / SYNC_INTERVAL) + 1;
ga_range_max = ones(1, sync_length) .* NCARRIERS;
ga_range_min = ones(1, sync_length);
ga_intcon = 1 : sync_length

ga_options = gaoptimset( ...
                      'Display'           , 'iter', ...
                      'PlotFcns'          , @gaplotbestf, ...
                      'PopulationSize'    , 20, ...
                      'PopInitRange'      , [ga_range_min; ga_range_max],...
                      'Generations'       , 50, ...
                      'CrossoverFraction' , 0.7,...
                      'TolFun'            , 0.0001, ...
                      'UseParallel'       , true...
                    )

[opt_result, min_M] = ga(@SS_GA_Loss, sync_length, [], [], [], [], ga_range_min, ga_range_max, [], ga_intcon, options)
