range_max = ones(1, sync_length) .* NCARRIERS;
range_min = ones(1, sync_length);
IntCon = 1 : sync_length

options = gaoptimset( ...
'Display', 'iter', ...
'PlotFcns', @gaplotbestf, ...
'PopulationSize', 20, ...
'PopInitRange', [range_min; range_max],...
'Generations', 50, ...
'CrossoverFraction', 0.7,...
'StallGenLimit', 10, ...
'TolFun', 0.0001, ...
'UseParallel', true...
)

[opt_result, min_M] = ga(@SS_GA_Loss, sync_length, [], [], [], [], range_min, range_max, [], IntCon, options)