function [fitresult, gof] = Noise_Fit(band_f_log, band_fa)
%CREATEFIT1(BAND_F_LOG,BAND_FA)
%  Create a fit.
%
%  Data for 'Band' fit:
%      X Input : band_f_log
%      Y Output: band_fa
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Jul-2019 19:25:06


%% Fit: 'Band'.
[xData, yData] = prepareCurveData( band_f_log, band_fa );

% Set up fittype and options.
ft = fittype( 'fourier6' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0 0 0 0 0 0 0 0 0 0 0 0 0 0.785398163397448];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Band' );
h = plot( fitresult, xData, yData );
legend( h, 'band_fa vs. band_f_log', 'Band', 'Location', 'NorthEast' );
% Label axes
xlabel band_f_log
ylabel band_fa
grid on


